### ISSUE TITLE
Candidates with contacts details for Twitter, but not email, do not appear under "tweet them all"

### ISSUE THREAD

**Issue by jonathandeamer** [frabcus/mpcv#35]
![image](https://cloud.githubusercontent.com/assets/202770/6765585/00f5709a-cfdf-11e4-9881-fb0dcf8a24b4.png)

On seeing the above Candidates page, I visited Your Next MP to add Twitter contact details for Przemek Skwirczynski. The Twitter username field is already correctly filled in at Your Next MP.

Probably confusing UI-wise to list Przemek Skwirczynski under "Not yet shared their CV" without full contact details, but would nonetheless be good to have the option to tweet him on clicking "tweet them all".

**Comment by frabcus** [comment]
Yes! I'm not sure how to present this right yet.

Currently, an MP can't upload their CV if we don't have their email, because we make them confirm it.

So there's not much point Tweeting them... Well, I guess there is, just to ask them for their email!

Will think about what to do - may change this page a lot anyway, thanks for feedback!

**Comment by jonathandeamer** [comment]
Ah of course - didn't think of the necessity of email from an ID verification point of view.

**Comment by frabcus** [comment]
I've noted to fix this as part of a larger redesign of this page. Closing this bug for now!
