### ISSUE TITLE
License notice should be given for YNMP data

### ISSUE THREAD

**Issue by tfgg** [frabcus/mpcv#51]
Attribution should be given somewhere on pages that use YNMP data, since it's CC-BY-SA.

Since MPCV is actually part of Democracy Club, I suppose this isn't strictly needed, but it's still nice and sets a good example :)

**Comment by frabcus** [comment]
I've just spent a bit of time trying to work out what attribution is actually legally required under CC, and it isn't particularly clear. This is because it is data - so stuff about copying what is on the original makes no sense. The original (`candidates.csv`) doesn't even have a license or any commentary on it!

> You may satisfy the conditions in Section 3(a)(1) in any reasonable manner based on the medium,
> means, and context in which You Share the Licensed Material. For example, it may be reasonable to
> satisfy the conditions by providing a URI or hyperlink to a resource that includes the required information. https://creativecommons.org/licenses/by-sa/4.0/legalcode

I think it is "reasonable based on the medium" (a web site) to put credit on the about page, and use a hyperlink. But I could be wrong!

I'd rather not add legalese to _every_ page - if going that way, I'd rather credit by linking to YourNextMP detailed pages. I'd rather not add copyright junk to _every_ page
